### ISSUE TITLE
App Name ambiguity

### ISSUE THREAD

**Issue by jsavage** [ruuvi/Android_RuuvitagScanner#15]
I am confused and I suspect others may also be about the version of the app I am running and whether I need to update it.  If its not already visible in the UI somewhere please could you add a version string.

Also, having uninstalled the previous version, when I try and install I am getting "There was a problem while parsing the package."  What is the most reliable method of installing this? I am downloading the apk and emailing it to myself on smartphone and installing from there.

**Comment by io53** [comment]
Since the last time the app was updated you can tell the version from sidebar -> About.

Downloading apk's can be problematic from some sources.
I'd suggest using https://github.com/ruuvi/Android_RuuvitagScanner/blob/master/RuuvitagScanner.apk for downloading the apk.
(You have to request desktop site to see the download button)

**Comment by jsavage** [comment]
many thanks for clarifying.
